image: Visual Studio 2017

environment:
  NUGET_API_KEY:
    secure: FPpv6TqhVgVqeQojuytzP0DJN4BVbVSxP+Z+sQAOT74ODts9aS0ypxpjO05hYXba

pull_requests:
  do_not_increment_build_number: true

build_script:
- ps: |
    & .\build.cmd AppVeyor NuGetPublicKey="$($Env:NUGET_API_KEY)" BuildVersion=git BuildNumber=$($Env:APPVEYOR_BUILD_NUMBER)

test: off

artifacts:
- path: build\NuGetPackages\*.nupkg
  name: NuGet
- path: build\NuGetPackages\*.snupkg
  name: NuGet

deploy: off

